In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
adult=pd.read_csv('C:\\Users\\user\\Desktop\\資料探勘作業一\\adult.csv',sep='\t')


adult.head()


age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  output  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [2]:
from sklearn.preprocessing  import LabelEncoder

le=LabelEncoder()

adult['workclass']=le.fit_transform(adult['workclass'])
adult['education']=le.fit_transform(adult['education'])
adult['marital-status']=le.fit_transform(adult['marital-status'])
adult['occupation']=le.fit_transform(adult['occupation'])
adult['relationship']=le.fit_transform(adult['relationship'])
adult['race']=le.fit_transform(adult['race'])
adult['sex']=le.fit_transform(adult['sex'])
adult['native-country']=le.fit_transform(adult['native-country'])
adult['output'] = le.fit_transform(adult['output'])
adult






age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1          2174             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0         15024             0   

       hours-per-week  native-country  output  
0                  40              39       0  
1                  13              39       0  
2                  40              39       0  
3                  40              39       0  
4                  40               5       0  
...               ...             ...     ...  
32556              38              39       0  
32557              40              39       1  
32558              40              39       0  
32559              20              39       0  
32560              40              39       1  

[32561 rows x 15 columns]

In [3]:
print(adult['output'].unique())
print(adult['workclass'].unique())
print(adult['education'].unique())
print(adult['marital-status'].unique())
print(adult['occupation'].unique())
print(adult['relationship'].unique())
print(adult['race'].unique())
print(adult['sex'].unique())
print(adult['native-country'].unique())


[0 1]
[7 6 4 1 2 0 5 8 3]
[ 9 11  1 12  6 15  7  8  5 10 14  4  0  3 13  2]
[4 2 0 3 5 1 6]
[ 1  4  6 10  8 12  3 14  5  7 13  0 11  2  9]
[1 0 5 3 4 2]
[4 2 1 0 3]
[1 0]
[39  5 23 19  0 26 35 33 16  9  2 11 20 30 22 31  4  1 37  7 25 36 14 32
  6  8 10 13  3 24 41 29 28 34 38 12 27 40 17 21 18 15]


In [4]:
adult.dtypes


age               int64
workclass         int32
fnlwgt            int64
education         int32
education-num     int64
marital-status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country    int32
output            int32
dtype: object

In [5]:
from sklearn.model_selection import train_test_split
#adult = adult[:5000].reset_index(drop=True)
X = adult.drop(labels=['hours-per-week'],axis=1).values
y = adult['hours-per-week'].values



#print('Train shape:', X_train.shape)
#print('Test shape:', X_test.shape)

In [6]:
from sklearn import svm
# 建立SVR模型
linearModel=svm.SVR(C=1, kernel='poly')
# 使用訓練資料訓練模型
linearModel.fit(X, y)
# 使用訓練資料預測
#predicted=linearModel.predict(X_test)

#print('Train Set:',linearModel.score(X_train,y_train))
#print('Test Set:',linearModel.score(X_test,y_test))

SVR(C=1, kernel='poly')

In [7]:
linearModel.predict(X)

array([40.10563895, 40.10042684, 40.0991183 , ..., 40.10003184,
       40.09935309, 40.63326933])

In [8]:
A=pd.read_csv('C:\\Users\\user\\Desktop\\adult.test.csv',sep='\t')
A

age      workclass  fnlwgt      education  education-num  \
0       25        Private  226802           11th              7   
1       38        Private   89814        HS-grad              9   
2       28      Local-gov  336951     Assoc-acdm             12   
3       44        Private  160323   Some-college             10   
4       18              ?  103497   Some-college             10   
...    ...            ...     ...            ...            ...   
16276   39        Private  215419      Bachelors             13   
16277   64              ?  321403        HS-grad              9   
16278   38        Private  374983      Bachelors             13   
16279   44        Private   83891      Bachelors             13   
16280   35   Self-emp-inc  182148      Bachelors             13   

            marital-status          occupation     relationship  \
0            Never-married   Machine-op-inspct        Own-child   
1       Married-civ-spouse     Farming-fishing          Husband   
2       Married-civ-spouse     Protective-serv          Husband   
3       Married-civ-spouse   Machine-op-inspct          Husband   
4            Never-married                   ?        Own-child   
...                    ...                 ...              ...   
16276             Divorced      Prof-specialty    Not-in-family   
16277              Widowed                   ?   Other-relative   
16278   Married-civ-spouse      Prof-specialty          Husband   
16279             Divorced        Adm-clerical        Own-child   
16280   Married-civ-spouse     Exec-managerial          Husband   

                      race      sex  capital-gain  capital-loss  \
0                    Black     Male             0             0   
1                    White     Male             0             0   
2                    White     Male             0             0   
3                    Black     Male          7688             0   
4                    White   Female             0             0   
...                    ...      ...           ...           ...   
16276                White   Female             0             0   
16277                Black     Male             0             0   
16278                White     Male             0             0   
16279   Asian-Pac-Islander     Male          5455             0   
16280                White     Male             0             0   

       hours-per-week  native-country   output  
0                  40   United-States   <=50K.  
1                  50   United-States   <=50K.  
2                  40   United-States    >50K.  
3                  40   United-States    >50K.  
4                  30   United-States   <=50K.  
...               ...             ...      ...  
16276              36   United-States   <=50K.  
16277              40   United-States   <=50K.  
16278              50   United-States   <=50K.  
16279              40   United-States   <=50K.  
16280              60   United-States    >50K.  

[16281 rows x 15 columns]

In [9]:
le=LabelEncoder()

A['workclass']=le.fit_transform(A['workclass'])
A['education']=le.fit_transform(A['education'])
A['marital-status']=le.fit_transform(A['marital-status'])
A['occupation']=le.fit_transform(A['occupation'])
A['relationship']=le.fit_transform(A['relationship'])
A['race']=le.fit_transform(A['race'])
A['sex']=le.fit_transform(A['sex'])
A['native-country']=le.fit_transform(A['native-country'])
A['output'] = le.fit_transform(A['output'])
A

age  workclass  fnlwgt  education  education-num  marital-status  \
0       25          4  226802          1              7               4   
1       38          4   89814         11              9               2   
2       28          2  336951          7             12               2   
3       44          4  160323         15             10               2   
4       18          0  103497         15             10               4   
...    ...        ...     ...        ...            ...             ...   
16276   39          4  215419          9             13               0   
16277   64          0  321403         11              9               6   
16278   38          4  374983          9             13               2   
16279   44          4   83891          9             13               0   
16280   35          5  182148          9             13               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               7             3     2    1             0             0   
1               5             0     4    1             0             0   
2              11             0     4    1             0             0   
3               7             0     2    1          7688             0   
4               0             3     4    0             0             0   
...           ...           ...   ...  ...           ...           ...   
16276          10             1     4    0             0             0   
16277           0             2     2    1             0             0   
16278          10             0     4    1             0             0   
16279           1             3     1    1          5455             0   
16280           4             0     4    1             0             0   

       hours-per-week  native-country  output  
0                  40              38       0  
1                  50              38       0  
2                  40              38       1  
3                  40              38       1  
4                  30              38       0  
...               ...             ...     ...  
16276              36              38       0  
16277              40              38       0  
16278              50              38       0  
16279              40              38       0  
16280              60              38       1  

[16281 rows x 15 columns]

In [10]:
print(A['output'].unique())
print(A['workclass'].unique())
print(A['education'].unique())
print(A['marital-status'].unique())
print(A['occupation'].unique())
print(A['relationship'].unique())
print(A['race'].unique())
print(A['sex'].unique())
print(A['native-country'].unique())


[0 1]
[4 2 0 6 1 7 5 8 3]
[ 1 11  7 15  0 14  5  9 12 10  4  8  6  2  3 13]
[4 2 6 0 5 3 1]
[ 7  5 11  0  8 10  3  1  4 13 12  9 14  6  2]
[3 0 1 4 5 2]
[2 4 1 3 0]
[1 0]
[38  0 28 13 25  6 20 11 29 36 14  8 32 39 34  4 23 18  1 30 24  9  5 35
 21  2 31  3 26 15 19 33 22  7 40 17 16 12 37 27 10]


In [11]:
X = A.drop(['hours-per-week'],axis=1)
y = A['hours-per-week']

In [12]:
B=linearModel.predict(X)
B

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


array([40.09886529, 40.10040466, 40.09514646, ..., 40.09314924,
       40.11761364, 40.09967078])

In [ ]:
plt.scatter(X_test,y_test)
plt.plot(X_test.ravel(),y_test, color="#d62728")
plt.title('kernel=linear')
plt.xlabel('True')
plt.ylabel('Predicted')

In [13]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y,B)
print("MAE: ",mae)

import math
MSE = np.square(np.subtract(y,B)).mean() 
RMSE = math.sqrt(MSE)
print("RMSE: ",RMSE)

mape =np.mean(np.abs((y - B) / y)) * 100
print("MAPE: ",mape)


MAE:  7.484236536729328
RMSE:  12.463067471837261
MAPE:  35.243170630093445


In [ ]:
from sklearn import svm

# 建立SVR模型
polyModel=svm.SVR(C=1, kernel='poly', degree=3, gamma='scale')
# 使用訓練資料訓練模型
polyModel.fit(X_train, y_train)
# 使用訓練資料預測
predicted=polyModel.predict(X_test)

print('Train Set:',polyModel.score(X_train,y_train))
print('Test Set:',polyModel.score(X_test,y_test))

In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,predicted)
print("MAE: ",mae)

import math
MSE = np.square(np.subtract(y_test,predicted)).mean() 
RMSE = math.sqrt(MSE)
print("RMSE: ",RMSE)

mape = mean_absolute_error(y_test,predicted)*100
print("MAPE: ",mape)

In [ ]:

from sklearn import svm

# 建立SVR模型
rbfModel=svm.SVR(C=1, kernel='rbf', gamma='auto')
# 使用訓練資料訓練模型
rbfModel.fit(X_train, y_train)
# 使用訓練資料預測
predicted=rbfModel.predict(X_test)

print('Train Set:',rbfModel.score(X_train,y_train))
print('Test Set:',rbfModel.score(X_test,y_test))

In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,predicted)
print("MAE: ",mae)

import math
MSE = np.square(np.subtract(y_test,predicted)).mean() 
RMSE = math.sqrt(MSE)
print("RMSE: ",RMSE)

mape = mean_absolute_error(y_test,predicted)*100
print("MAPE: ",mape)